server:
    port: 8080
    servlet:
        context-path: /api

spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
        
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3308/myTiktok
        driverClassName: "com.mysql.cj.jdbc.Driver"
    jpa:
        hibernate:
            ddl-auto: update    
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    mail: 
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: localhost
            port: 6379
            password: ${REDIS_PASSWORD}

b2:
    keyId: ${BUCKET_KEY_ID}
    applicationKey: ${BUCKET_APPLICATION_KEY}
    videoBucketName: ${BUCKET_VIDEO_NAME}
    videoBucketId: ${BUCKET_VIDEO_ID}

    imageBucketName: ${BUCKET_IMAGE_NAME}
    imageBucketId: ${BUCKET_IMAGE_ID}

jwt:
    valid-duration: 18000
    refreshable-duration: 100000
