server:
    port: 8080

spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3308/myTiktok
        driverClassName: "com.mysql.cj.jdbc.Driver"
    jpa:
        hibernate:
            ddl-auto: update    
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    mail: 
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: localhost
            port: 6379
            password: ${REDIS_PASSWORD}


jwt:
    valid-duration: 3000
    refreshable-duration: 2000
